- import_role:
    name: utils/install
  vars:
    pacman:
      - cmake
      - pkgconf
      - kitty
      - sddm
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
      - swayidle
      - grim
      - slurp
      - brightnessctl
      - pavucontrol
      - wl-clipboard
      - ttf-firacode-nerd
    yay:
      - hyprland
      - hyprpaper-git
      - xdg-desktop-portal-hyprland-git
      - sddm-theme-aerial-git
      - swaylock-effects-git
      - avizo

- name: Create config directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.config/{{ item }}"
    owner: root
    group: root
    state: directory
    mode: '0755'
  loop:
    - 'hypr'
    - 'hypr/scripts'

- name: Copy hyprland config files
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/hypr/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - "binds.conf"
    - "exec.conf"
    - "general.conf"
    - "hyprland.conf"
    - "hyprpaper.conf"
    - "input.conf"

- name: Copy hyprland scripts
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/hypr/{{ item }}"
    owner: root
    group: root
    mode: '0755'
  loop:
    - "scripts/brightness.sh"
    - "scripts/eww.sh"
    - "scripts/idle.sh"
    - "scripts/lock.sh"
    - "scripts/screensharing.sh"
    - "scripts/volume.sh"

- name: Create sddm directory
  become: yes
  ansible.builtin.file:
    path: "/etc/sddm.conf.d"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy sddm theme config
  become: yes
  ansible.builtin.copy:
    src: "theme.conf"
    dest: "/etc/sddm.conf.d/theme.conf"
    owner: root
    group: root
    mode: '0644'

- name: Start SDDM 
  become: yes
  ansible.builtin.systemd:
    state: started
    name: sddm

