all:
  children:
    workstations:
      hosts:
        xps:
        desktop:
          ansible_host: workstation.d.local.olsen.cloud
        micropc:
          ansible_host: micropc.d.local.olsen.cloud
      vars:
        os_desktop_enable: true
        os_auth_pw_max_age: 99999
        os_ignore_users: ['aur_builder']
        sysctl_custom_config:
          kernel.unprivileged_userns_clone: 1 # required for flatpak
