all:
  vars:
    github_user: morten-olsen
  children:
    workstations:
      hosts:
        xps:
        desktop:
          ansible_host: workstation.d.local.olsen.cloud
        micropc:
          ansible_host: micropc.d.local.olsen.cloud
      vars:
        os_desktop_enable: true
        os_auth_pw_max_age: 99999
        os_ignore_users: ['aur_builder']
        hidepid_option: "0"
        sysctl_overwrite:
          # Enable IPv4 traffic forwarding.
          net.ipv4.ip_forward: 1 # Docker needs this https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening#docker-support
        sysctl_custom_config:
          kernel.unprivileged_userns_clone: 1 # required for flatpak
