all:
  children:
    workstations:
      hosts:
        xps:
          hostname: xps.d.local.olsen.cloud
        desktop:
          hostname: workstation.d.local.olsen.cloud
        micropc:
          hostname: micropc.d.local.olsen.cloud
