- name: Harden
  hosts: all
  become: yes
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
  vars:
    os_auditd_enabled: false

- name: Workstation
  hosts: workstations
  become: no
  roles:
    - utils/battery
    - modern/terminal
    - modern/desktop
