
- name: Workstation
  hosts: workstations
  become: no
  tasks:
    - include_role:
        name: utils/upgrade
    - include_role:
        name: utils/battery
    - include_role:
        name: modern/terminal
    - include_role:
        name: modern/desktop
