
- name: Copy nvm shell files
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.shellrc/rc.d/{{ item }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: '0644'
  loop:
    - "01-nvm.sh"
    - "05-npm.sh"

- name: Checkout nvm 
  become: yes
  become_user: "{{ current_user }}"
  ansible.builtin.git:
    repo: 'https://github.com/nvm-sh/nvm'
    dest: "{{ home }}/.nvm"

- name: Install node
  become: yes
  become_user: "{{ current_user }}"
  shell: 
    cmd: source {{ home }}/.nvm/nvm.sh && nvm install 18
