- import_role:
    name: utils/install
  vars:
    names:
      - kitty

- name: Create config directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.config/{{ item }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    state: directory
    mode: "0755"
  loop:
    - "kitty"
- name: Copy hyprland config files
  become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home }}/.config/kitty/{{ item }}"
    owner: "{{ root_user }}"
    group: "{{ root_group }}"
    mode: "0644"
  loop:
    - "kitty.conf"
