- name: Enable SSH in firewall
  become: yes
  when: use_ufw
  community.general.ufw:
    rule: allow
    interface: wg0
    direction: in
    to_port: '22'

- name: Disable empty password login
  become: yes
  lineinfile: 
    dest: "/private/etc/ssh/sshd_config" 
    regexp: '^#?PermitEmptyPasswords' 
    line: 'PermitEmptyPasswords no'

- name: Disable remote root login
  become: yes
  lineinfile: 
    dest: "/private/etc/ssh/sshd_config" 
    regexp: '^#?PermitRootLogin' 
    line: 'PermitRootLogin no'

- name: Disable password login
  become: yes
  lineinfile: 
    dest: "/private/etc/ssh/sshd_config" 
    regexp: '^(#\s*)?PasswordAuthentication '
    line: 'PasswordAuthentication no'

- name: Start SSHD
  become: yes
  when: use_systemd
  ansible.builtin.systemd:
    state: restarted
    name: sshd 

- name: Create ssh config directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.ssh"
    owner: "{{ root_user }}" 
    group: "{{ root_group }}" 
    state: directory
    mode: '0755'

- name: Setup authorized keys
  become: yes
  ansible.builtin.get_url:
    url: "https://github.com/{{ github_user }}.keys"
    dest: "{{ home }}/.ssh/authorized_keys"
    owner: "{{ root_user }}" 
    group: "{{ root_group }}" 
    mode: '0644'
  when: github_user is defined
#
# - name: Enable PAM
#   lineinfile: 
#     dest: "/private/etc/ssh/sshd_config" 
#     regexp: '^#?UsePAM' 
#     line: 'UsePAM yes'
#   notify: restart sshd
