- name: Create shell script directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.shellrc"
    owner: "{{ root_user }}" 
    group: "{{ root_group }}"
    state: directory
    mode: '0755'

- name: Create shell script directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.shellrc/rc.d"
    owner: "{{ root_user }}" 
    group: "{{ root_group }}"
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  become: yes
  ansible.builtin.copy:
    src: bashrc
    owner: "{{ root_user }}" 
    group: "{{ root_group }}"
    dest: "{{ home }}/.bashrc"
    mode: '0644'
