- name: Create shell script directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.shellrc"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Create shell script directory
  become: yes
  ansible.builtin.file:
    path: "{{ home }}/.shellrc/rc.d"
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: Copy file with owner and permissions
  become: yes
  ansible.builtin.copy:
    src: bashrc
    dest: "{{ home }}/.bashrc"
    owner: root
    group: root
    mode: '0644'
